### ISSUE TITLE
Actualización de RoadMap

### ISSUE THREAD

**Issue by milo19980525** [udistrital/evaluacion_cliente#227]
Teniendo en cuenta los líneamientos establecidos para la contratación 2023 de la oficina apoyar técnicamente en la creación del [roadmap](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7Bc8b13929-fc88-4ea1-b494-60b97b651bf8%7D&action=default&cid=667f4e85-63ba-4622-bdf7-15f1837bcd84) para proyectos Core.

**Especificaciones técnicas**

- Establecer las actividades y subactividades del roamap relacionadas con los features actuales y en prospectiva.
- Tener en cuenta una estimación inicial en puntos de historia.
- Agrupar las actividades y subactividades en milestones o sprints teniendo en cuenta la disponibilidad del equipo.

**Sub Tareas**

- [x] Realizar la definición de actividades y subactividades asociadas a los hitos 2, 3, 4 y 5
- [x] Establecer en SP la estimación de las actividades y sibactividades definidas.
- [ ] Agrupar actividades y subactividades en milestones teniendo en cuenta la capacidad del equipo asumiendo dos desarrolladores tiempo completo y uno parcial.

**Criterios de aceptación**

- [x] Comentario en issue que proporcione un resumen de las actividades agregadas al roadmap diariamente.
- [ ] Actualización de actividades en el roadmap.

**Requerimientos**

- [ ] Especificación de requerimientos (En dado caso de no tenerlos refinados aún colocar estimación inical)

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by a52290451** [comment]
Se realiza actualización del RoadMap agregando los siguientes hitos e items de trabajo:

**Hito 1:** Interoperabilidad con Sistemas externos (SIGEP, SIDEAP)

WI 1: Desarrollo en AGORA para WS de consulta de datos basicos a través de Sideap_mid
WI 2: Desarollo en AGORA para lógica de carga de datos basicos y datos complementarios en formulario de registro.

**Hito 3:** Implementar política de firma electrónica (No mediante rúbrica)

Feature: Implementación y entrega de servicio de firma electrónica

WI 1: Adaptación de modulo de evaluaciones de cumplimiento para agregar evaluadores por numero de cedula
WI 2: Implementar servicio de firma electrónica para Evaluaciones de cumplimiento
WI 3: Pruebas funcionales de firma electrónica en evaluaciones y certificaciones.
WI 4: Despliegue de modificiaciones en evaluaciones y gestor_documental_mid a ambiente de producción.

Feature: Optimizacion de servicio de firma electrónica

WI 1: Reducción de tamaño de firma electrónica estampada en documentos.
WI 2: Agregar restricciones a PDF firmado - Firma electrónica

**Hito 4:** Análisis y plan de trabajo de migración de funcionalidades en APIs depreciadas

WI 1: Creación de listado de APIs depreciadas, en proceso de depreciación y que deben ser depreciadas.
WI 2:  Completar formato de ruta de migración de servicios en APIs depreciadas PARTE 2.
WI 3: Llenado de formato "Resumen de migración de servicios" en APIs depreciadas PARTE 2.
WI 4: Completar formato excel de conexiones por API para APIs depreciadas PARTE 2.
WI 5: Actualización de grafo de conexiones con información asociada a APIs depreciadas PARTE 2.

**Hito 5:** Módulo de notificaciones

Feature: Mantenimiento y optimización

WI 1: Mantenimiento Módulo de Notificaciones
WI 2: Optimización tiempos de respuesta de notificaciones.

Feature: Notificaciones entre sistemas

WI 1: Análisis de comunicación entre sistemas y entre roles por sistema para envio de notificaciones.
WI 2: Desarrollo de método para enviar notificaciones de un Topic, asociado a un sistema, a otro, mediante un servicio expuesto por notificacion_mid
WI 3: Desarrollo de lógica para consumir servicio de notificaciones entre sistemas y enviar notificaciones
WI 4: Desarrollo de lógica para consumir servicio de notificaciones entre sistemas, recibir y mostrar notificaciones

Feature: Notificaciones por correo electrónico sin dependencia de Topic

WI 1: Análisis sobre servicios de correo electrónico para implementar notificaciones directas.
WI 2: Desarrollo de lógica para nuevo servicio de notificaciones por correo en notificacion_mid
WI 3: Desarrollo de lógica para consumir nuevo servicio de notificaciones por correo desde un sistema

**Hito 6:** Modulo de verificación y validación de documentos con firma electrónica

Feature: Creación modulo de verificación de documentos

WI 1: Análisis y planeación de módulo de verificaicón y validación de documentos con firma electrónica.
WI 2: Creación de cliente de verificaicón de documentos con su estructura base y despliegue en ambiente de pruebas
WI 3: Creación de menú y vista para verificar documentos por firma electrónica.
WI 4: Consumo de API gestor_documental_mid para verificación de documentos
WI 5: Desarrollo de lógica para procesamiento y validación de documentos
WI 6: Salida de información con resultado de proceso de verificación del documento.
WI 7: Despliegue modulo de verificación de documentos en ambiente de producción

Con esto se completa parcialmente el RoadMap de desarrollos en CORE.

Link RoadMap: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=c2IRyY

**Comment by a52290451** [comment]
Se realiza actualización de RoadMap, creando una nueva página para el módulo de plantillas, incluyendo la planeación inicial de Hitos e items de trabajo relacionados:

**Hito 1:** Creación módulo de plantillas

Feature: Estructura general

WI 1: Diseño módulo de plantillas
WI 2: Creación de HUs para módulo de plantillas
WI 3: Análisis y diseño de BDs para módulo de plantillas
WI 4: Creación de BDs para módulo de plantillas
WI 5: Creación API plantillas_crud con su estructura base y despliegue en ambiente de pruebas
WI 6: Creación API plantillas_mid con su estructura base y despliegue en ambiente de pruebas
WI 7: Creación de cliente de plantillas con su estructura base y despliegue en ambiente de pruebas

Feature: Plantillas minuta

WI 1: Diseño y planeación de módulo de plantillas minuta
WI 2: Identificación de fuentes de información requeridas y dependencias del módulo.
WI 3: Creación de vista para crear y editar plantillas minuta.
WI 4: Desarrollo de controladores y helpers en plantillas_mid para obtener información requerida en la creación y edición de plantillas minuta.
WI 5: Carga de información en el cliente para visualización base de plantillas minuta (modo edición)
WI 6: Tratamiento de información recolectada en el cliente para creación de una plantilla.
WI 7: Tratamiento de información recolectada en el cliente para modificación de minutas en una plantilla
WI 8: Vista de documento final en pdf, tras modificaciones o creación de una plantilla, con opción para descargar.
WI 9: Almacenamiento y replicación de información de plantillas minuta a BDs y APIs correspondientes.
WI 10: Despliegue modulo de plantillas minuta en ambiente de producción

Con esto se completa parcialmente el RoadMap de desarrollos en el módulo de plantillas, quedando pendiente su planeación y posterior ajuste de items de trabajo.

Link RoadMap: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=zraUBg

**Comment by a52290451** [comment]
Se realiza la creación de los issues:

1. #220 
2. #228 
3. #229 
4. #230

**Comment by a52290451** [comment]
Se realiza actualización de Roadmap para CORE:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=oKOBVC

Se realiza actualización parcial de Roadmap para el Módulo de Plantillas:

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=Ia7x0o

**Comment by a52290451** [comment]
Se completa actualización de RoadMap para el módulo de plantillas:

[https://udistritaleduco-my.sharepoint.com/❌/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=Ia7x0o](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=Ia7x0o)

**Comment by a52290451** [comment]
Se actualiza el roadmap con el detalle de los items de trabajo del Hito 6:  Modulo de verificación y validación de documentos con firma electrónica.

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=zzopqG&nav=MTVfe0FGNDY0NjcxLUU4QjEtNEVDRS1BREFCLTdCQzg1NjE0MzE0MX0

Además, se crean los issues:

1. [Diseño de módulo de verificación de documentos con firma electrónica.](https://github.com/udistrital/verificacion_cliente/issues/2)
2. [Creación de cliente de verificación de documentos con su estructura base y despliegue en ambiente de pruebas.](https://github.com/udistrital/verificacion_cliente/issues/3)
3. [Creación de vista "Verificación de documentos".](https://github.com/udistrital/verificacion_cliente/issues/4)

**Comment by a52290451** [comment]
Se completa creación de Issues con su respectivo detalle para el Hito 6: Modulo de verificación y validación de documentos con firma electrónica.

1. [Desarrollo de lógica para consumir API gestor_documental_mid y verificar documentos.](https://github.com/udistrital/verificacion_cliente/issues/5)
2. [Salida de información con resultado de proceso de verificación del documento.](https://github.com/udistrital/verificacion_cliente/issues/6)
3. [Pruebas funcionales del proceso de verificación.](https://github.com/udistrital/verificacion_cliente/issues/7)
4. [Despliegue modulo de verificación de documentos en ambiente de producción.](https://github.com/udistrital/verificacion_cliente/issues/8)
